name: 'input_switch'
lam_type: 'constant'
lam_params: {val: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4]}
network: [[1, 1, 0, 0, 0, 0],[0, 0, 1, 1, 0, 0],[0, 0, 0, 0, 1, 1]]
mu: [[1., 1., 0, 0, 0, 0],[0, 0, 1., 1., 0, 0],[0, 0, 0, 0, 1., 1.]]
h: [1, 1, 1, 1, 1, 1]
init_queues: [0, 0, 0, 0, 0, 0]
queue_event_options: [[1., 0, 0, 0, 0, 0],[0, 0, 0, 0, 0, 0],[0., 0, 1., 0, 0, 0],[0, 0, 0, 0, 0, 0],[0, 0, 0, 0, 1, 0],[0., 0, 0, 0, 0, 0],[-1., 0, 0, 1., 0, 0],[0, -1., 0, 0, 0, 0],[0, 0, -1, 0, 0, 0],[0, 0, 0, -1, 1, 0],[0, 0, 0, 0, -1, 0],[0, 1, 0, 0, 0, -1]]
train_T: 30000
test_T: 50000
num_pool: 1
