name: 'n_model'
lam_type: 'constant'
lam_params: {val: [0.38, 1.235]}
network: [[1,1],[0,1]]
mu: [[1, 0.5], [0,1]]
server_pool_size: [1, 1]
h: [1,3]
init_queues: [0, 0]
queue_event_options: null
train_T: 3
test_T: 3 