name: 'reentrant_3_hyper'
env_type: 'reentrant_3'
service_type: 'hyper'
lam_type: 'hyper'
lam_params: {val: null, scale: 0.8}
network: null
mu: null
h: [1,1,1,1,1,1,1,1,1]
init_queues: [0,0,0,0,0,0,0,0,0]
queue_event_options: 'custom'
train_T: 30000
test_T: 80000
num_pool: 1

  

  
